reboot: sudo and IP variable with IF ping added.

diff --git a/reboot b/reboot
--- a/reboot
+++ b/reboot
@@ -1,5 +1,13 @@
 #!/bin/bash
 #reboot
 
-sshpass -p pi ssh pi@192.168.178.33 sudo reboot
-echo "rebooting..."
+IP='192.168.178.33'
+sudo sshpass -p pi ssh pi@$IP sudo reboot
+fping -cl -t500 $IP 2>/dev/null 1>/dev/null
+
+if [ "$?" = 0 ]
+then 
+  echo "Error"
+else
+  echo "$IP Rebooting "
+fi
